name: audiobooks
description: A new Flutter project.

version: 1.0.1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  audio_service: ^0.18.0
  audioplayers: ^0.20.1
  cached_network_image: ^3.1.0
  flutter:
    sdk: flutter
  flutter_html: ^2.1.2
  http: ^0.13.3
  just_audio: ^0.9.12
  path_provider: ^2.0.5
  provider: ^6.0.1
  rxdart: ^0.27.2
  shared_preferences: ^2.0.8
  sqflite: ^2.0.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

# dependency_overrides:
#   audioplayers:
#     git:
#       url: https://github.com/lohanidamodar/audioplayers
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Aleo
      fonts:
        - asset: assets/fonts/Aleo-Regular.ttf
        - asset: assets/fonts/Aleo-Italic.ttf
          style: italic
        - asset: assets/fonts/Aleo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Aleo-Light.ttf
          weight: 300
    - family: Slabo
      fonts:
        - asset: assets/fonts/Slabo27px-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
