name: audiobooks
description: A new Flutter project.

version: 1.0.1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  # flutter_downloader: ^1.1.7
  path_provider: ^1.1.0
  sqflite: ^1.1.5
  flutter_html: ^0.10.1+hotfix.1
  provider: ^3.0.0+1
  audioplayer: ^0.5.2
  cached_network_image: ^1.0.0
  audio_service: ^0.3.0
  rxdart: ^0.22.0
  shared_preferences: ^0.5.3+2
  audioplayers: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  audio_service:
    path: ../audio_service
  audioplayer:
    path: ../audioplayer


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Aleo
      fonts:
        - asset: assets/fonts/Aleo-Regular.ttf
        - asset: assets/fonts/Aleo-Italic.ttf
          style: italic
        - asset: assets/fonts/Aleo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Aleo-Light.ttf
          weight: 300
    - family: Slabo
      fonts:
        - asset: assets/fonts/Slabo27px-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
